backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: string}
          - {label: "Subtitle", name: "subtitle", widget: string}
          - {label: "Image", name: "image", widget: image}
          - label: "Why"
            name: "why"
            widget: object
            fields:
              - {label: "Heading", name: "heading", widget: string}
              - {label: "Text", name: "text", widget: markdown}
              - {label: "Button", name: "button", widget: object, fields: [
                  {label: "Text", name: "text", widget: string},
                  {label: "Link", name: "link", widget: string}]}
          - {label: "How", name: "how", widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: markdown}]}
          - {label: "About", name: "about", widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: markdown}]}
