backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: string}
          - {label: "Subtitle", name: "subtitle", widget: string}
          - {label: "Meta", name: "meta", widget: object, fields: [
              {label: "Description", name: "description", widget: text},
              {label: "Keywords", name: "keywords", widget: string},
              {label: "Social card image", name: "socialcard", widget: image}]}
          - {label: "Image", name: "image", widget: image}
          - {label: "Email", name: "email", widget: string}
          - {label: "Phone", name: "phone", widget: string}
          - {label: "KvK", name: "kvk", widget: string}
          - label: "Why"
            name: "why"
            widget: object
            fields:
              - {label: "Heading", name: "heading", widget: string}
              - {label: "Text", name: "text", widget: markdown}
              - {label: "Button", name: "button", widget: object, fields: [
                  {label: "Text", name: "text", widget: string},
                  {label: "Link", name: "link", widget: string}]}
          - {label: "How", name: "how", widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: markdown}]}
          - label: "References"
            name: "references"
            widget: object
            fields:
              - {label: "Intro", name: "intro", widget: string}
              - label: "Logos"
                name: "logos"
                widget: list
                fields:
                  - {label: "Logo", name: "logo", widget: image}
                  - {label: "Link", name: "link", widget: string}
          - {label: "Quote", name: "quote", widget: object, fields: [
              {label: "Text", name: "text", widget: markdown},
              {label: "Author", name: "author", widget: string}]}
          - {label: "About", name: "about", widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Image", name: "image", widget: image},
              {label: "Text", name: "text", widget: markdown}]}
